### ISSUE TITLE
How to generate "data tables" from chart?

### ISSUE THREAD

**Issue by sunnyville** [JasonObeid/Chart2Text#14]
Hi,

This may be obvious but how do I actually generate "data tables" for my charts that I have generated using matplotlib and seaborn? 

So I have a csv dataset file that I read with Pandas into a DataFrame and then use Matplotlib (sometimes Seaborn) to generate charts. However, I have no idea how to generate "data tables" from these charts so I can use this library to generates summaries for the charts.

I've searched around for an answer but I'm unable to find it, so I'd be really grateful for the help.

Thanks.

**Comment by JasonObeid** [comment]
Hi,

Honestly it will be quite a bit of work.

The easiest way would be to "mock" the output of running templatepreprocess.py, i.e convert your dataset to a txt file, where each line represents one chart. Within the line, for each "cell" in the chart's data, you would convert it to the format "AXIS_LABEL|VALUE|AXIS_TYPE|CHART_TYPE". See the following for an example from: https://raw.githubusercontent.com/JasonObeid/Chart2Text/master/data/test/testData.txt

> Country|Singapore|x|bar_chart Average_number_of_children_per_woman|1.38|y|bar_chart Country|Republic_of_Korea|x|bar_chart Average_number_of_children_per_woman|1.44|y|bar_chart

Then you will need to store your titles in a txt file also, where line 1's title is for the same chart as line 1 of the data. i.e https://raw.githubusercontent.com/JasonObeid/Chart2Text/master/data/test/testTitle.txt

Once you transform your dataset into this format, you can follow the steps in the [Generation](https://github.com/JasonObeid/Chart2Text#generation) section of the docs.

1. You would have to download the model
2. Run model/summarize.py using your transformed dataset to convert the data to text. The text will contain "data variables" which will need to be replaced by your actual data in the next step. See [Here](https://github.com/JasonObeid/Chart2Text/blob/master/results/aug17/templateOutput-p80.txt) for an example.
3. Run etc/summaryComparison.py to substitute the variables predicted. You may need to make changes in the script.

Good luck!

**Comment by sunnyville** [comment]
@JasonObeid Thank you so much for this prompt and detailed reply. I was able to follow along with your instructions and I believe I understand how it all works now. 

I first tested the procedure of generating text using the testdata as outlined in the [Generation](https://github.com/JasonObeid/Chart2Text#generation) section of the docs. However, for some reason the results generated don't match with the data that is inputted to the model. The first time I tried with all the test data and then to confirm and simplify it further I tried with just one sample from the test data, and here are the detail of what happened:

I removed everything from `testData.txt` and `testTitle.txt`, except for the first item. The contents of the two files looked like this:
`testTitle.txt`:
```
Countries with the lowest fertility rate globally 2050 to 2055
```
`testData.txt`:
```
Country|Singapore|x|bar_chart Average_number_of_children_per_woman|1.38|y|bar_chart Country|Republic_of_Korea|x|bar_chart Average_number_of_children_per_woman|1.44|y|bar_chart Country|United_Arab_Emirates|x|bar_chart Average_number_of_children_per_woman|1.45|y|bar_chart Country|Puerto_Rico|x|bar_chart Average_number_of_children_per_woman|1.45|y|bar_chart Country|Bosnia_and_Herzegovina|x|bar_chart Average_number_of_children_per_woman|1.47|y|bar_chart Country|Saint_Lucia|x|bar_chart Average_number_of_children_per_woman|1.48|y|bar_chart Country|Greece|x|bar_chart Average_number_of_children_per_woman|1.5|y|bar_chart Country|Cyprus|x|bar_chart Average_number_of_children_per_woman|1.51|y|bar_chart Country|Italy|x|bar_chart Average_number_of_children_per_woman|1.51|y|bar_chart Country|Republic_of_Moldova|x|bar_chart Average_number_of_children_per_woman|1.52|y|bar_chart Country|China_Taiwan_Province_of_China|x|bar_chart Average_number_of_children_per_woman|1.53|y|bar_chart Country|Albania|x|bar_chart Average_number_of_children_per_woman|1.53|y|bar_chart Country|Mauritius|x|bar_chart Average_number_of_children_per_woman|1.54|y|bar_chart Country|Thailand|x|bar_chart Average_number_of_children_per_woman|1.54|y|bar_chart Country|Qatar|x|bar_chart Average_number_of_children_per_woman|1.56|y|bar_chart Country|Nepal|x|bar_chart Average_number_of_children_per_woman|1.56|y|bar_chart Country|Croatia|x|bar_chart Average_number_of_children_per_woman|1.56|y|bar_chart Country|Japan|x|bar_chart Average_number_of_children_per_woman|1.57|y|bar_chart Country|Serbia|x|bar_chart Average_number_of_children_per_woman|1.57|y|bar_chart Country|Brazil|x|bar_chart Average_number_of_children_per_woman|1.58|y|bar_chart Country|North_Macedonia|x|bar_chart Average_number_of_children_per_woman|1.58|y|bar_chart Country|Brunei_Darussalam|x|bar_chart Average_number_of_children_per_woman|1.59|y|bar_chart Country|Portugal|x|bar_chart Average_number_of_children_per_woman|1.59|y|bar_chart Country|Spain|x|bar_chart Average_number_of_children_per_woman|1.59|y|bar_chart Country|Canada|x|bar_chart Average_number_of_children_per_woman|1.59|y|bar_chart
```

Then I ran the following command:
```
python model/summarize.py --model_path aug17-80.pth --table_path data/test/testData.txt --output_path results/temp/tempOut.txt --title_path data/test/testTitle.txt --beam_size 4 --batch_size 8
```

This is what the content of the output file `tempOut.txt` looked like:
```
This statistic shows templateYLabel[0] templateYLabel[1] in leading economies worldwide in templateTitleDate[0] . In the templateXValue[6] templateXValue[16] , templateYLabel[0] templateYLabel[1] stood at templateYValue[16] templateYLabel[2] templateYLabel[3] templateYLabel[4] templateYLabel[5] templateYLabel[6] . In the templateXValue[6] , templateYLabel[0] users paid templateYValue[6] templateYLabel[2] templateYLabel[3] templateYLabel[4] templateYLabel[5] templateYLabel[6] .
```

As you can see, the input data was about a chart related to "Countries with the lowest fertility rates", but the model seems to be outputting the text not related to this, but something related to leading economies.

There seems to be a clear miss match here and I'm not sure what I'm doing wrong.

**Comment by JasonObeid** [comment]
@sunnyville This mismatch you see is an expected behaviour, you didn't do anything wrong.

The language model which is predicting these words doesn't know anything about the topic, or even what the caption should be.

Given the input data, the model outputs what it considers to be the best word to predict (i.e, based on what is was trained on). It won't give a correct / good prediction for each word in a sentence.

**Comment by sunnyville** [comment]
@JasonObeid Thanks! I'm working on creating the data tables now.
